<!DOCTYPE factura [
    <!ELEMENT factura (datos-emisor, datos-cliente, detalle-factura)>
    <!ATTLIST factura numero ID #REQUIRED fecha CDATA #REQUIRED>
    <!ELEMENT datos-emisor (nombre, cif, telefono)>
    <!ELEMENT datos-cliente (nombre, cif, telefono)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cif (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT detalle-factura (linea+)>
    <!ATTLIST detalle-factura importe CDATA #REQUIRED>
    <!ELEMENT linea (descripcion, cantidad, pvp, oferta?)>
    <!ATTLIST linea codigo-articulo ID #REQUIRED tipo (Libro | DVD | Varios) #REQUIRED>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT pvp (#PCDATA)>
    <!ELEMENT oferta EMPTY>
]>
<factura numero="F20240403" fecha="2025-04-03">
    <datos-emisor>
        <nombre>Librer√≠a La Esquina</nombre>
        <cif>ES12345678X</cif>
        <telefono>987654321</telefono>
    </datos-emisor>
    <datos-cliente>
        <nombre>Biblioteca Barrio Norte</nombre>
        <cif>ES87654321Y</cif>
        <telefono>123456789</telefono>
    </datos-cliente>
    <detalle-factura importe="59.90">
        <linea codigo-articulo="A001" tipo="Libro">
            <descripcion>Historia de un pueblo</descripcion>
            <cantidad>2</cantidad>
            <pvp>19.95</pvp>
            <oferta/>
        </linea>
        <linea codigo-articulo="A002" tipo="DVD">
            <descripcion>Documental sobre aves</descripcion>
            <cantidad>1</cantidad>
            <pvp>20.00</pvp>
        </linea>
    </detalle-factura>
</factura>